### PR TITLE
Bloodsucker Integrations

### PR DESCRIPTION
**Pull request by park66665**
## About The Pull Request

It makes things actually work:

1. you can now no longer run when at fortitude. (ported from fulp)
2. the bloodsucker body temperature finally are at room temperature except when masquerading. (kinda ported from fulp)
3. NONATURALHEAL related changes ported from fulp. (blocks some heals despite trait name)
4. Bloodsuckers now recognize each other through examine tabs. (ported from fulp)
5. Examining pale skin is now Bloodsucker-ready. (ported from fulp)
6. Masquerading vampires now appear 100% blood on health analyzers. (sorta ported from fulp)

## Why It's Good For The Game

1. Makes Bloodsucker more functional
2. The change which Terra yells at you decreases
3. I couldn't add these as proposed changes so I am doing it this way

## Changelog
:cl:
fix: I am sure this is absolutely meaningless, but hey, I fixed bloodsucker a little
/:cl:

### CODE REVIEW

**Comment by park66665** [comment]
@coolsurf6 plz lok at dis

**Comment by coolsurf6** [comment]
What in the god damn. I'll look st this Not At 1am

**Comment by park66665** [comment]
ahhh, okay, no pressure

**Comment by coolsurf6** [comment]
Having a look at this, the thing I'm a bit scared of is that there are alot of edits to base code. It somehow needs to be modularized and it is gonna be fucking spicy...

**Pull request merged**
